---
version: '3.42.1'

tasks:

  update:
    desc: Update project dependencies and submodules
    cmds:
      - git submodule update --remote
      - "jq '{mcpServers: .servers}' .vscode/mcp.json > .mcp.json"